name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout  ️
              uses: actions/checkout@v2.3.1

            - name: lock npm version
              uses: actions/setup-node@v3
              with:
                  node-version: 16.20.0

            - name: Install and Build
              run: |
                  npm i -g pnpm@8.15.8
                  pnpm run init
                  pnpm run docs:build
              env:
                  NODE_OPTIONS: '--max_old_space_size=4096'

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  BRANCH: gh-pages
                  FOLDER: docs/.vuepress/dist
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN1 }}
